apiVersion: v1
kind: Service
metadata:
  name: rust-string-outputter-svc
spec:
  type: NodePort
  selector:
    app: rust-string-outputter
  ports:
    - name: http
      nodePort: 30080
      port: 2345
      protocol: TCP
      targetPort: 8080
